---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/ninja --version
      register: ninja_test_output
    - name: ninja --version
      debug:
        msg: '{{ ninja_test_output.stdout }}'
