---
- name: Testing andrewrothstein.ninja
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'ninja --version'
      ansible.builtin.command: /usr/local/bin/ninja --version
      changed_when: false
      register: ninja_test_output
    - name: Output of 'ninja --version'
      ansible.builtin.debug:
        msg: '{{ ninja_test_output.stdout }}'
