---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Install os dependent pkgs...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ ninja_os_pkgs | default([]) }}'
    state: present
- name: Checking for install at {{ ninja_install_ver_dir }}...
  become: true
  ansible.builtin.stat:
    path: '{{ ninja_install_ver_dir }}'
  changed_when: false
  register: ninja_binary
- name: Downloading and installing ninja
  when: not ninja_binary.stat.exists
  block:
    - name: Downloading {{ ninja_url }} to {{ ninja_fq_lzip }}...
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ ninja_url }}'
        dest: '{{ ninja_fq_lzip }}'
        checksum: '{{ ninja_checksum }}'
        mode: '644'
    - name: Mkdir {{ ninja_install_ver_dir }}...
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ ninja_install_ver_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive into {{ ninja_install_ver_dir }}...
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ ninja_fq_lzip }}'
        dest: '{{ ninja_install_ver_dir }}'
        creates: '{{ ninja_install_fq_exe }}'
  always:
    - name: Cleanup {{ ninja_fq_lzip }}...
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ ninja_fq_lzip }}'
        state: absent
- name: Linking {{ ninja_install_fq_exe }} to {{ ninja_install_fq_link }}...
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ ninja_install_fq_exe }}'
    dest: '{{ ninja_install_fq_link }}'
    state: link
